# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Close Stale Pull Requests

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  pull-requests: write
  issues: write

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v5
        with:
          days-before-stale: 15
          days-before-close: 30

          stale-pr-label: stale

          stale-pr-message: >
            This pull request has been marked as stale because it has been inactive
            for more than 15 days. Please update it or it will be automatically
            closed in 15 days.

          close-pr-message: >
            This pull request has been automatically closed due to inactivity.
            Feel free to reopen it if you still plan to work on it.
